apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mongo-express-deployment-ingress
  namespace: mongodb
spec:
  rules:
  - host: vr.myapp.com
    http:
      paths:
      - path: /mongoExpress
        pathType: Prefix
        backend:
          service:
            name: mongo-express-service
            port:
              number: 80 #port of the service mongo-express-service. Which then redirects to its own target port.