apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
  namespace: mongodb
spec:
  selector:
    app: mongo-express
  type: LoadBalancer #External
  ports:
  - protocol: TCP
    port: 80 ## Service port. Not the port of the actual application but this service can be anything
    targetPort: 8081
    nodePort: 30001 ##Connect from browser